"""drop_status_from_transactions

Revision ID: 6bf0f8578784
Revises: d2f7a1b9c8de
Create Date: 2026-03-06 14:35:18.564543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bf0f8578784'
down_revision: Union[str, Sequence[str], None] = 'd2f7a1b9c8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('status', postgresql.ENUM('pending', 'posted', name='transactionstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
